---
name: my-secureblue
description: This is my personal OS image.
base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest
modules:
- type: files
  files:
  - source: system
    destination: /
- type: rpm-ostree
  install:
  - cabal-install
  - conda
  - emacs
  - emacs-json-mode
  - emacs-magit
  - emacsclient
  - ghc-Diff-devel
  - ghc-aeson-pretty-devel
  - ghc-concurrent-output-devel
  - ghc-constraints-devel
  - ghc-erf-devel
  - ghc-lifted-base-devel
  - ghc-megaparsec-devel
  - ghc-mmorph-devel
  - ghc-pretty-show-devel
  - ghc-resourcet-devel
  - ghc-silently-devel
  - ghc-unliftio-devel
  - git
  - happy
  - python3-ramalama
  - stack
  - strace
  - zfs-fuse
- type: default-flatpaks
  configurations:
    - notify: true
      install:
        - com.vscodium.codium
        - io.appflowy.AppFlowy
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.gnome.Boxes
        - org.kde.akregator
        - org.kde.kcalc
        - org.signal.Signal
- type: signing
- type: yafti
- type: script
  scripts:
  - "install-little_shell_scripts.sh"
  - "install-lossless-cut.sh"
  - "install-sort-yaml-seqs.sh"
  - "patch-yafti-config.sh"
