---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: my-secureblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    # repos:
    #   - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - cabal-install
      - conda
      - emacs
      - emacs-json-mode
      - emacs-magit
      - emacsclient
      - ghc
      - git
      - python3-ramalama
      - stack
      - strace
      - zfs-fuse

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.vscodium.codium
        - io.appflowy.AppFlowy
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.gnome.Boxes
        - org.kde.akregator
        - org.kde.kcalc
        - org.signal.Signal
      # remove:
      #   - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    scripts:
      - "install-lossless-cut.sh"
      - "install-little_shell_scripts.sh"
      - "patch-yafti-config.sh"